spring.application.name=BookMyTrip

spring.datasource.url=jdbc:postgresql://localhost:5432/bmt
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update